# theme: argvus-light-veil
background              #f7f7f7
foreground              #181818
cursor                  #181818
cursor_text_color       #f7f7f7
selection_foreground    #181818
selection_background    #c7c7c7
active_tab_background   #ebebeb
active_tab_foreground   #181818
inactive_tab_background #e7e7e7
inactive_tab_foreground #5a5a5a

background_opacity 0.90
