# theme: frost-float
background              #F6F8FA
foreground              #24292F
cursor                  #0969DA
cursor_text_color       #FFFFFF
selection_foreground    #24292F
selection_background    #DDF4FF
active_tab_background   #F1F4F7
active_tab_foreground   #24292F
inactive_tab_background #EFF2F5
inactive_tab_foreground #57606A

background_opacity 0.90
